### ISSUE TITLE
Buscar y sistematizar por decada los mapas de las vias ferroviarias en Argentina

### ISSUE THREAD

**Issue by diegogentilepassaro** [diegogentilepassaro/Train#1]
Objetivo:
Buscar y sistematizar por decada los mapas de las vias ferroviarias en Argentina

Entregable:
Listado de mapas en excel, con fuente, link, y descripción básica.

**Comment by jobelmar** [comment]
Avances al Feb 13, 2019:
- Se encontraron una serie de mapas historicos en Internet (ver google Drive: train\images)
- Conclusion 1: parece ser que la data que necesitamos existe y puede ser de muy buena calidad
- Conclusion 2: debemos determinar que datos/mapas son suficientes para investigacion (en terminos de covertura temporal-geografica, informacion cualitativa, resolucion). Esto requiere mayor desarrollo de la idea de investigacion, en especial pregunta y estrategia de identificacion. Por lo tanto, la tarea de recoleccion de mapas sigue abierta, pero lo damos prioridad a la propuesta de investigacion.
