### ISSUE TITLE
Digitalizar Mapa de caminos de 1970

### ISSUE THREAD

**Issue by diegogentilepassaro** [diegogentilepassaro/Train#11]
[Objetivo]
Tener un shapefile con los caminos de 1970 digitalizados en una definición

[Pasos]
1. Georeferenciar imágenes de mapas 1970 del automóvil club.[Completeado]
2. Dibujar las lineas de los caminos teniendo en cuenta las siguientes cuatro categorías de una variable llamada type:
  - Pavimento (código 1)
  - Consolidado (código 2)
  - Tierra (código 3)
  - Huella de camino (código 4)

[Notas importantes]
- La definición del dibujo de las líneas tiene que ser similar al shapefile de ejemplo de 1986 que ya fue digitalizado por nosotros.
- Hay un shapefile con la red vial actual que es muy util para saber dónde están muchos de los caminos. Por favor usarlo para dibujar las líneas mejor.
- También ayuda usar los puntos del shapefile de asentamientos humanos.

**Comment by diegogentilepassaro** [comment]
Algunos comentarios después de ver los shapefiles que enviaste:
 - Vimos que hay una categoría 5. qué vendría a ser? 
 - Comparando con el shapefile del 86 vimos que estas dibujando las lineas con una definición un poco peor. 
 - Varios caminos que claramente coinciden con algunos caminos que estaban presentes en la red vial del 86 o en la actual están dibujados un poco corridos. Por favor, siempre que se puede comparar con la red val actual o con nombres de asentamientos humanos y/o localidades hay que tener cuidado y dibujar los caminos donde están realmente y no solo seguir el dibujo del mapa.

**Comment by stestino95** [comment]
La categoría 5 es "en construcción", no supe de qué otra forma marcarlo. Voy a estar más atento a comparar con la red actual y del 86 en lo que quede digitalizar, y corregir lo ya hecho. No debería afectar a los plazos acordados

**Comment by diegogentilepassaro** [comment]
Dale genial muchas gracias! 💪🏻

Con respecto a usar la categoría 5 para en construcción: lo que teníamos en mente es que si es un camino de pavimento en construcción lo marques con el código 1, y si fuese de consolidado con un 2 y así sucesivamente.

**Comment by stestino95** [comment]
Actualizacion 17/8: tuve problemas por la mañana para trabajar por problemas con la pc. Termine por hoy, mañana desde las 11 finalizo la capa, me queda el area de Buenos Aires y corregir algunas cosas previas.

**Comment by stestino95** [comment]
Buenas! Tarea terminada, subo la capa a la carpeta compartida del drive, reemplazando el archivo existente. Aguardo instrucciones para la otra tarea asignada ayer

**Comment by diegogentilepassaro** [comment]
Buenas Stefano! Gracias por completar esta tarea a tiempo 👍 

Ahora voy a mirar la capa y usarla y si tenemos algún comentario te avisamos.

**Comment by diegogentilepassaro** [comment]
@stestino95 la capa está genial así que voy a cerrar esta tarea.

Gracias!
