### ISSUE TITLE
definir fecha de proximar reunion

### ISSUE THREAD

**Issue by jobelmar** [diegogentilepassaro/Train#3]

**Comment by jobelmar** [comment]
que tal 1 o 2 semanas?

**Comment by diegogentilepassaro** [comment]
Perfecto! Hagamosla el miercoles 6 de febrero. A mi me viene bien o a las 8/8:30am  hasta las 10/10:30 o a las 12 para el almuerzo hasta las 2.

**Comment by jobelmar** [comment]
demosle el 6 de Febrero; yo puedo de 8am a 9am, o de 1pm a 2pm. alguna preferencia?

**Comment by jobelmar** [comment]
Manana, 1pm!
