### ISSUE TITLE
Plotear serie de tiempo de deuda y/o GDP contra kilometros totales de vias de tren y/o calidad del material ferroviario

### ISSUE THREAD

**Issue by diegogentilepassaro** [diegogentilepassaro/Train#4]

**Comment by jobelmar** [comment]
Podriamos usar periodificacion de Lopez (2007) - "historia del ferrocarril en la argentina":

* 1857-1886: Pragmatismo: publico y privado; nacional y provincial - primeras lineas
* 1887-1916: Empresas extranjeras + control statal
* 1917-1946: Del equilibrio a la crisis de las empresas ferroviarias privadas
* 1947-1976: De la nacionalizacion a los planes de modernizacion
* 1977-2006: El ciclo de las reformas traumaticas
